### ISSUE TITLE
Version 2.0.1 detector module won't load in PyMoDaq 4

### ISSUE THREAD

**Issue by NanjeofKro** [rgeneaux/pymodaq_plugins_stellarnet#1] opened 2023-07-26 11:23 UTC
I have recently installed version 2.0.1 of pymodaq_plugins_stellarnet for my PyMoDaq 4 installation. When trying to run a test preset with the 1D Detector mdule, the PyMoDaq launch screen comes up but the message "Loading det module: Det XX" is displayed indefinitely, with the GUI never launching. I have tried leaving it running for 1h without result. The error only occurs when including stellarnet detectors in the preset, and did not occur in the 1.x versions of the plugin used with PyMoDaq 3. I am running Windows 10, Python 3.10.9, PyQt 5.15.9. Do you know what could be causing the issue? Thank you in advance!

**Comment by rgeneaux** [comment] 2023-07-26 12:03
Hi and thanks for using the plugin!

I checked and putting the stellarnet in a preset works on my setup (pymodaq_plugins_stellarnet=2.0.1, pymodaq=4.0.6, python=3.8.0)!
Can you tell me: 
- does the plugin work in a simple daq_viewer?
- can you copy and paste the log file that you get when you launch the dashboard?  (to access the log file: in dashboard top menu, "File/Show log file", or click the blue "i" button in a daq_move/viewer)

**Comment by NanjeofKro** [comment] 2023-07-26 14:20
The plugin does not work in daq_viewer; I get the following output:

INFO:pymodaq.pymodaq.daq_viewer.Testing:  File "C:\Users\ADMIN\anaconda3\envs\pmd4_env\lib\site-packages\pymodaq_plugins_stellarnet\daq_viewer_plugins\plugins_1D\daq_1Dviewer_Stellarnet.py", line 216, in ini_detector
    name = usb.util.get_string(
  File "C:\Users\ADMIN\anaconda3\envs\pmd4_env\lib\site-packages\usb\util.py", line 260, in get_string
    return buf[2:buf[0]].tostring().decode('utf-16-le')
'array.array' object has no attribute 'tostring'
INFO:pymodaq.pymodaq.daq_viewer.Testing:detector initialized: False

I've added the log file output below for launching the dashboard and initialising my test preset (which contains one mock 1D detector, one mock actuator stage, and one Stellarnet 1D detector):

2023-07-26 16:04:56,965 - pymodaq - INFO - 
2023-07-26 16:04:56,965 - pymodaq - INFO - 
2023-07-26 16:04:56,965 - pymodaq - INFO - ************************
2023-07-26 16:04:56,965 - pymodaq - INFO - Starting PyMoDAQ modules
2023-07-26 16:04:56,965 - pymodaq - INFO - ************************
2023-07-26 16:04:56,965 - pymodaq - INFO - 
2023-07-26 16:04:56,965 - pymodaq - INFO - 
2023-07-26 16:04:56,965 - pymodaq - INFO - ************************
2023-07-26 16:04:56,965 - pymodaq - INFO - Setting Qt backend to: pyqt5 ...
2023-07-26 16:04:56,965 - pymodaq - INFO - ************************
2023-07-26 16:04:56,965 - pymodaq.daq_utils - INFO - ************************
2023-07-26 16:04:56,965 - pymodaq.daq_utils - INFO - pyqt5 Qt backend loaded
2023-07-26 16:04:56,965 - pymodaq.daq_utils - INFO - ************************
2023-07-26 16:04:56,965 - pymodaq - INFO - 
2023-07-26 16:04:56,965 - pymodaq - INFO - 
2023-07-26 16:04:56,965 - pymodaq - INFO - ************************
2023-07-26 16:04:56,965 - pymodaq - INFO - Setting Locale to English / UnitedStates
2023-07-26 16:04:56,965 - pymodaq - INFO - ************************
2023-07-26 16:04:56,965 - pymodaq - INFO - 
2023-07-26 16:04:56,965 - pymodaq - INFO - 
2023-07-26 16:04:56,965 - pymodaq - INFO - ************************
2023-07-26 16:04:56,965 - pymodaq - INFO - Initializing the pint unit register
2023-07-26 16:04:56,965 - pymodaq - INFO - ************************
2023-07-26 16:04:57,645 - pymodaq - INFO - 
2023-07-26 16:04:57,645 - pymodaq - INFO - 
2023-07-26 16:04:57,785 - pymodaq._1d_scanners - INFO - adaptive module is not present, no adaptive scan possible
2023-07-26 16:04:57,785 - pymodaq._2d_scanners - INFO - adaptive module is not present, no adaptive scan possible
2023-07-26 16:04:57,805 - pymodaq.viewer0D_plugins - WARNING - daq_0Dviewer_MockAdaptive plugin couldn't be loaded due to some missing packages or errors: cannot import name 'ScanParameters' from 'pymodaq.utils.scanner' (C:\Users\ADMIN\anaconda3\envs\pmd4_env\lib\site-packages\pymodaq\utils\scanner\__init__.py)
2023-07-26 16:04:59,061 - pymodaq.daq_logger - INFO - To enable logging to database install: sqalchemy and sqlalchemy_utils packages as well as the backend for your specific database, for instance psycopg2 for PostGreSQL database
2023-07-26 16:04:59,241 - pymodaq.remote_manager - WARNING - Could not load pygame module, no joystick configurable
2023-07-26 16:04:59,811 - pymodaq.dashboard - INFO - Initializing Dashboard
2023-07-26 16:05:00,201 - pymodaq.dashboard - INFO - Dashboard Initialized
2023-07-26 16:05:00,461 - pymodaq.dashboard - ERROR - Error while checking the available PyMoDAQ version
Traceback (most recent call last):
  File "C:\Users\ADMIN\anaconda3\envs\pmd4_env\lib\site-packages\pymodaq\dashboard.py", line 1272, in check_version
    available_version = [version_mod.parse(ver) for ver in get_pypi_pymodaq('pymodaq')['versions']]
KeyError: 'versions'
2023-07-26 16:06:59,955 - pymodaq.dashboard - INFO - Loading Preset file: C:\ProgramData\.pymodaq\preset_configs\test4_spectrometer.xml
2023-07-26 16:07:00,107 - pymodaq.pymodaq.daq_move.Move 00 - INFO - Initializing DAQ_Move: Move 00
2023-07-26 16:07:01,312 - pymodaq.pymodaq.daq_move.Move 00 - INFO - Stage initialized: True info: Mock stage
2023-07-26 16:07:01,452 - pymodaq.pymodaq.daq_viewer.Det 01 - INFO - Initializing DAQ_Viewer: Det 01
2023-07-26 16:07:03,114 - pymodaq.pymodaq.daq_viewer.Det 01 - INFO - detector initialized: True
2023-07-26 16:07:03,124 - pymodaq.dashboard - ERROR - 'DAQ_Viewer' object has no attribute 'viewers_docks'
Traceback (most recent call last):
  File "C:\Users\ADMIN\anaconda3\envs\pmd4_env\lib\site-packages\pymodaq\dashboard.py", line 1072, in set_preset_mode
    actuators_modules, detector_modules = self.set_file_preset(filename)
  File "C:\Users\ADMIN\anaconda3\envs\pmd4_env\lib\site-packages\pymodaq\dashboard.py", line 766, in set_file_preset
    self.add_det(plug_name, plug_settings, det_docks_settings, det_docks_viewer,
  File "C:\Users\ADMIN\anaconda3\envs\pmd4_env\lib\site-packages\pymodaq\dashboard.py", line 607, in add_det
    detector_modules[-1].viewers_docks[-1])
AttributeError: 'DAQ_Viewer' object has no attribute 'viewers_docks'

**Comment by rgeneaux** [comment] 2023-07-26 15:07
Hi,

I was able to reproduce your issue when upgrading to python 3.9 or 3.10. It looks like the plugin works only in python 3.8, because of the old version of pyusb that the constructor requires. Hopefully they will upgrade this at some point. I'll add a note in the readme to explain that.

Would downgrading to python 3.8 be ok for you? If so, I think it will fix your issue.

Anyway thanks for the bug report, always appreciated!
Romain

**Comment by NanjeofKro** [comment] 2023-07-26 16:50
Downgrading made it possible to run the daq_viewer; however, running it from a preset in the dashboard gives the same error as before:

ERROR:pymodaq.dashboard:'DAQ_Viewer' object has no attribute 'viewers_docks'
Traceback (most recent call last):
  File "C:\Users\ADMIN\anaconda3\envs\pmd4_env\lib\site-packages\pymodaq\dashboard.py", line 1072, in set_preset_mode
    actuators_modules, detector_modules = self.set_file_preset(filename)
  File "C:\Users\ADMIN\anaconda3\envs\pmd4_env\lib\site-packages\pymodaq\dashboard.py", line 766, in set_file_preset
    self.add_det(plug_name, plug_settings, det_docks_settings, det_docks_viewer,
  File "C:\Users\ADMIN\anaconda3\envs\pmd4_env\lib\site-packages\pymodaq\dashboard.py", line 607, in add_det
    detector_modules[-1].viewers_docks[-1])
AttributeError: 'DAQ_Viewer' object has no attribute 'viewers_docks'

**Comment by rgeneaux** [comment] 2023-07-28 12:06
Hi,
I think I managed to reproduce your bug: it only happens when you have two detectors in a preset, correct? This happens on my computer even with two Mock detectors. 
If so, this is a bug with Pymodaq v4 (still in development), not with the stellarnet plugin. Could you go to the Pymodaq main repo (https://github.com/PyMoDAQ/PyMoDAQ) and post an issue with your error there? Sebastien will probably be able to fix this easily, but I don't know the code enough myself for that.

**Comment by rgeneaux** [comment] 2023-08-29 11:23
Hi,
the issue with the dashboard was fixed in https://github.com/PyMoDAQ/PyMoDAQ/pull/138 but not released as a new version yet.
you can either wait for the next release that will incorporate this fix, or update your installation from github 
cheers
Romain

**Closed as completed by rgeneaux** 2023-08-29 11:23 UTC
